### ISSUE TITLE
Precarga de apps

### ISSUE THREAD

**Issue by fpiecho** [fpiecho/TprofFiuba#2]
Que cree las apps vacías, no con la precarga default de ionic

**Comment by LeandroRodriguez** [comment]
No entendi esto. No queres que se pueda arrancar con las otras 2 app tupes default? solo blank?

**Comment by fpiecho** [comment]
Sí, pero cuando creas una app de tabs por ejemplo, te lo crea con 3 tabs con textos y giladas, te lo debería crear con un único tab vacío supongo.

**Comment by fpiecho** [comment]
Esto al final no lo hice porque viéndolo bien me parece mejor que se cree con una precarga
